services:
  solr:
    image: solr:9.10.1
    container_name: xckan-docker-solr
    environment:
      VERBOSE: "no"
    ports:
      - "28983:8983"
    volumes:
      - type: volume
        source: solr_volume
        target: /var/solr
    command: 
      - solr-precreate
      - ckan-xsearch

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-xckan-docker}
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-xckan-docker}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-xckan-docker@example.com}
    container_name: xckan-docker-backend
    ports:
      - "25000:5000"
    depends_on:
      - "solr"
    volumes:
      - type: volume
        source: backend_volume
        target: /ext
      - type: bind
        source: ./backend
        target: /app/
    environment:
      XCKAN_ALLOWED_HOSTS: ${XCKAN_ALLOWED_HOSTS:-*}
      XCKAN_SYSTEM_NAME: ${XCKAN_SYSTEM_NAME}
      XCKAN_SYSTEM_FROM: ${XCKAN_SYSTEM_FROM}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xckan-docker-frontend
    ports:
      - "23000:3000"
    tty: true
    environment:
      SERVER_PORT: ${FRONTEND_PORT:-3000}
      SERVER_HOST: ${FRONTEND_HOST:-0.0.0.0}
      NUXT_BACKEND_API_BASE_URL: ${PRIVATE_BACKEND_API_URL:-http://backend:5000/api}
      NUXT_PUBLIC_BACKEND_API_BASE_URL: ${PUBLIC_BACKEND_API_URL:-http://localhost:25000/api}
      NUXT_PUBLIC_FRONTEND_WEB_BASE_URL: ${FRONTEND_WEB_URL:-http://localhost:23000}

volumes:
  solr_volume: {}
  backend_volume: {}
