version: '3.7'
services:
  solr:
    image: solr:latest
    container_name: xckan-docker-solr
    environment:
      VERBOSE: "no"
    ports:
      - "28983:8983"
    volumes:
      - solr_volume:/var/solr
    command:
      - solr-precreate
      - ckan-xsearch

  backend:
    build:
      context: ./backend
      args:
        XCKAN_BACKEND_SRC: https://www2.info-proto.com/xckan/ckan-xsearch-0.9.20220328.tar.gz
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-xckan-docker}
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-xckan-docker}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-xckan-docker@example.com}
    container_name: xckan-docker-backend
    ports:
      - "25000:5000"
    depends_on:
      - "solr"
    volumes:
      - backend_volume:/ext
    environment:
      XCKAN_ALLOWED_HOSTS: ${XCKAN_ALLOWED_HOSTS:-localhost}

  frontend:
    build:
      context: ./frontend
      args:
        XCKAN_FRONTEND_SRC: https://www2.info-proto.com/xckan/sip2-ckan-0.9.20220328.tar.gz
        SERVER_HOST: ${FRONTEND_HOSTS:-0.0.0.0}
        BACKEND_API: ${BACKEND_API:-http://localhost:25000/api}
        API_LOG:
    container_name: xckan-docker-frontend
    ports:
      - "23000:3000"

volumes:
  solr_volume: {}
  backend_volume: {}
