# Generated by Django 3.2.12 on 2023-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_add_tag_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='datalistfile_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='データ一覧ファイルURL'),
        ),
        migrations.AlterField(
            model_name='site',
            name='ckanapi_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='API URL'),
        ),
    ]
