# Generated by Django 3.2.12 on 2023-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_add_datalistfile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='datalist_convert_task',
            field=models.TextField(blank=True, null=True, verbose_name='データリスト変換タスク'),
        ),
    ]
