# Generated by Django 5.2.10 on 2026-02-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_datalist_convert_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ckanapi_apitoken',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='APIトークン'),
        ),
    ]
